### ISSUE TITLE
[Question] Interface boundaries violated in CartItem model? 

### ISSUE THREAD

**Issue by erback** [avosalmon/modular-monolith-laravel#7]
Hi! Thanks for an awseome Demo on laracon - me and my team will take a lot of inspiration from this in our works going forward. I just have a quick question that came in to mind when browsing the repository. The CartItem model inside the Order Domain references and foreging key relation in another domain (product - Inventory). Is this a bug or a feature? I'm curious since to me it seems that interface boundaries are violated?

**Comment by kamilkozak** [comment]
@erback I am wondering about that too. Do you already know why this is so?
